import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demoqa.com/');
  await page.locator('div:nth-child(2) > div > .avatar > svg').click();
  await page.getByText('Practice Form').click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('joe');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('dohn');
  await page.getByRole('textbox', { name: 'name@example.com' }).click();
  await page.getByRole('textbox', { name: 'name@example.com' }).fill('joe.dohn@gmùail.com');
  await page.getByText('Other').click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('123456789');
  await page.locator('#dateOfBirthInput').click();
  await page.getByRole('option', { name: 'Choose Monday, March 31st,' }).click();
  await page.locator('.subjects-auto-complete__value-container').click();
  await page.locator('#subjectsInput').fill('tests logicielles');
  await page.getByText('Sports').click();
  await page.getByRole('textbox', { name: 'Select picture' }).click();
  //await page.getByRole('textbox', { name: 'Select picture' }).setInputFiles('planning.png');
  await page.getByRole('textbox', { name: 'Select picture' }).click();
  await page.getByRole('textbox', { name: 'Select picture' }).setInputFiles([]);
  await page.getByRole('textbox', { name: 'Select picture' }).click({
    button: 'right'
  });
  await page.getByRole('textbox', { name: 'Current Address' }).click();
  await page.getByRole('textbox', { name: 'Current Address' }).fill('avenue du parc ');
  await page.locator('#state svg').click();
  await page.getByText('Haryana', { exact: true }).click();
  await page.getByText('Select City').click();
  await page.getByText('Karnal', { exact: true }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('1234567899');
  await page.getByRole('button', { name: 'Submit' }).click();
  // await page.getByRole('textbox', { name: 'name@example.com' }).click();
  // await page.getByRole('textbox', { name: 'name@example.com' }).press('ArrowLeft');
  // await page.getByRole('textbox', { name: 'name@example.com' }).press('ArrowLeft');
  // await page.getByRole('textbox', { name: 'name@example.com' }).press('ArrowLeft');
  // await page.getByRole('textbox', { name: 'name@example.com' }).press('ArrowLeft');
  // await page.getByRole('textbox', { name: 'name@example.com' }).press('ArrowLeft');
  // await page.getByRole('textbox', { name: 'name@example.com' }).press('ArrowLeft');
  // await page.getByRole('textbox', { name: 'name@example.com' }).press('ArrowLeft');
  // await page.getByRole('textbox', { name: 'name@example.com' }).fill('joe.dohn@gmail.com');
  // await page.getByRole('button', { name: 'Submit' }).click();
  // await page.getByRole('cell', { name: 'joe dohn' }).click();
  // await page.getByRole('cell', { name: 'joe.dohn@gmail.com' }).click();
  // await page.getByRole('cell', { name: 'Other' }).click();
  // await page.getByRole('cell', { name: '1234567899' }).click();
  // await page.getByRole('cell', { name: 'March,2025' }).click();
  // await page.getByRole('cell').filter({ hasText: /^$/ }).click();
  // await page.getByRole('cell', { name: 'Sports' }).click();
  // await page.getByRole('cell', { name: 'avenue du parc' }).click();
  // await page.getByRole('cell', { name: 'Haryana Karnal' }).click();
  // await page.getByRole('cell', { name: 'planning.png' }).click();
});